"""Contract layer: primitive aliases, typed errors (see common.py).

Full contract modules (rules, utility, tile, action, event, observation)
arrive in WP-02; only SPEC 2.1/3 bootstrap content exists now.
"""

from __future__ import annotations

from hydra2.contracts.common import (
    ActionId,
    BeliefEpochId,
    CanonicalizationError,
    ContractError,
    CorruptArtifactError,
    DeadlineExceededError,
    DeterminismError,
    DigestMismatchError,
    DigestText,
    Hydra2Error,
    IllegalActionError,
    IncompatibleSchemaError,
    InvalidActionError,
    InvalidTileError,
    LineageError,
    PacketId,
    PacketPartitionError,
    ParentId,
    ProposalSupportError,
    QualificationRequiredError,
    QuarantinedError,
    RulesMismatchError,
    RunId,
    SchemaVersion,
    Seat,
    SequenceNo,
    StaleBeliefError,
    TileId,
    TileType,
    UtcTimestamp,
    VisibilityViolationError,
)

__all__ = [
    "ActionId",
    "BeliefEpochId",
    "CanonicalizationError",
    "ContractError",
    "CorruptArtifactError",
    "DeadlineExceededError",
    "DeterminismError",
    "DigestMismatchError",
    "DigestText",
    "Hydra2Error",
    "IllegalActionError",
    "IncompatibleSchemaError",
    "InvalidActionError",
    "InvalidTileError",
    "LineageError",
    "PacketId",
    "PacketPartitionError",
    "ParentId",
    "ProposalSupportError",
    "QualificationRequiredError",
    "QuarantinedError",
    "RulesMismatchError",
    "RunId",
    "SchemaVersion",
    "Seat",
    "SequenceNo",
    "StaleBeliefError",
    "TileId",
    "TileType",
    "UtcTimestamp",
    "VisibilityViolationError",
]
