from __future__ import annotations

import argparse

from hydra_learner.data.raw_mjai import raw_mjai_config_from_args


def json_config(args: argparse.Namespace, effective_raw_mjai_max_samples: int | None = None) -> dict[str, object]:
    return {
        "variant": args.variant,
        "loss_mode": args.loss_mode,
        "batch": args.batch,
        "microbatch": args.microbatch,
        "hidden": args.hidden,
        "blocks": args.blocks,
        "bottleneck": args.bottleneck,
        "actions": args.actions,
        "residual_profile": args.residual_profile,
        "backbone_profile": args.backbone_profile,
        "conv_memory_format": args.conv_memory_format,
        "warmup": args.warmup,
        "steps": args.steps,
        "profile": args.profile,
        "profile_coarse": args.profile_coarse,
        "torch_profiler_trace": str(args.torch_profiler_trace) if args.torch_profiler_trace else None,
        "torch_profiler_start_step": args.torch_profiler_start_step,
        "torch_profiler_stop_step": args.torch_profiler_stop_step,
        "manifest": str(args.manifest) if args.manifest else None,
        "check_shard_files": args.check_shard_files,
        "lr": args.lr,
        "min_lr": args.min_lr,
        "lr_schedule": args.lr_schedule,
        "lr_warmup_steps": args.lr_warmup_steps,
        "schedule_total_steps": args.schedule_total_steps,
        "schedule_target_games": args.schedule_target_games,
        "grad_clip_norm": args.grad_clip_norm,
        "weight_decay": args.weight_decay,
        "adam_beta1": args.adam_beta1,
        "adam_beta2": args.adam_beta2,
        "adam_eps": args.adam_eps,
        "adamw_foreach": args.adamw_foreach,
        "adamw_fused": args.adamw_fused,
        "out": str(args.out),
        "w_oracle_critic": args.w_oracle_critic,
        "w_safety_residual": args.w_safety_residual,
        "w_exit": args.w_exit,
        "w_deltaq": args.w_deltaq,
        "compile_fullgraph_check": args.compile_fullgraph_check,
        "checkpoint_out": str(args.checkpoint_out) if args.checkpoint_out else None,
        "checkpoint_dir": str(args.checkpoint_dir) if args.checkpoint_dir else None,
        "keep_step_checkpoints": args.keep_step_checkpoints,
        "resume": str(args.resume) if args.resume else None,
        "checkpoint_every_steps": args.checkpoint_every_steps,
        "log_dir": str(args.log_dir) if args.log_dir else None,
        "log_every_steps": args.log_every_steps,
        "tensorboard_dir": str(args.tensorboard_dir) if args.tensorboard_dir else None,
        "tensorboard_url": args.tensorboard_url,
        "validation_steps": args.validation_steps,
        "validation_max_samples": args.validation_max_samples,
        "validation_every": args.validation_every,
        "validation_source_mode": args.validation_source_mode,
        "ema": None
        if not args.ema_enabled
        else {
            "enabled": True,
            "decay": args.ema_decay,
            "start_step": args.ema_start_step,
            "update_every_steps": args.ema_update_every_steps,
            "device": args.ema_device,
        },
        "raw_mjai": raw_mjai_config_from_args(args),
        "effective_raw_mjai_max_samples": effective_raw_mjai_max_samples,
        "quiet": args.quiet,
    }
