#!/usr/bin/env python3
"""B3 seal-replay driver: corpus in -> JCS-only manifests out + report JSON.

Migration step 3. Replays packaged manifests through the Rust NEW-form
(JCS, serde_jcs =0.2.0) printer and the ingest/decode/validate/quarantine
chain, then fails closed on any divergence.

Replay seal authority is Rust ONLY (`hydra-feed rows::remint_manifest_jcs`,
`rederive_joins`, `replay_corpus`; `feed::canon` + `feed::digest`). This
script performs NO replay/JCS seal math itself — it stages inputs (the only
Python seal math is TODAY-oracle minting for `--init-synthetic` staging,
which the Rust helpers then discard and re-mint), invokes the Rust helpers
via the `seal_replay_driver_hook` nextest entry (the feed crate ships no
binary, so the hook is the subprocess bridge), runs the rows KAT gate, and
checks the report. Single printer per commit holds: the JCS direction pin
(`jcs_is_new_not_caller_order_b3`) stays in Rust.

- synthetic e2e 3 objects: generated by `--init-synthetic DIR` (raw +
  archive_member + precompressed; shape-valid placeholder ids — Rust
  discards and re-mints JCS-only);
- lineage fixtures: any materialized `*.manifest.jsonl` (e.g. WP-04B
  lineage shapes) passed via `--corpus`;
- real manifests: packager `*.manifest.jsonl` outputs passed via
  `--real-manifest` (read in place; artifacts resolve next to the real
  manifest through the hook's canonical-parent rule).

Usage (from the repo root, ``pixi run python`` so ``hydra2`` resolves):
  pixi run python scripts/seal_replay.py --corpus <dir|file>... --out <dir>
  pixi run python scripts/seal_replay.py --init-synthetic /tmp/synth \\
      --corpus /tmp/synth --out /tmp/replay-out
  pixi run python scripts/seal_replay.py --corpus <dir> \\
      --real-manifest /path/to/real.manifest.jsonl --artifact-root /path/to/out \\
      --out <dir> --seal-only

Real packager manifests store bare relative compressed_path entries whose
artifacts live under the packager output root (ingest output_root); pass
that root via --artifact-root. Self-contained corpus dirs (synthetic,
lineage) resolve next to their manifest and need no flag.
Fail-closed: exit 1 on SealMismatch / DuplicatePath / container / count
(or hash/length/artifact/JSON) divergence, hook failure, red KAT gate, or
malformed report; exit 2 on operator error (missing inputs, missing cargo,
unwritable out). Exit 0 iff the report is green.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKSPACE = REPO_ROOT / "crates"
HOOK_FILTER = "seal_replay_driver_hook"
ROWS_GATE_FILTER = "rows::"

EXIT_OK = 0
EXIT_DIVERGENCE = 1
EXIT_USAGE = 2


def _fail_usage(message: str) -> int:
    print(f"seal_replay: error: {message}", file=sys.stderr)
    return EXIT_USAGE


def _synthetic_corpus(dst: Path) -> Path:
    """Generate the 3-object synthetic corpus (raw/archive/precompressed).

    Content digests/lengths/counts are real (hashlib/zstandard over actual
    bytes); the stored seal id is a shape-valid placeholder the Rust
    helpers discard and re-mint JCS-only. This staging performs NO seal
    math — replay authority is Rust-only.
    """
    try:
        import zstandard as zstd
    except ModuleNotFoundError:
        print(
            "seal_replay: error: --init-synthetic needs the zstandard package "
            "(pixi env provides it)",
            file=sys.stderr,
        )
        raise SystemExit(EXIT_USAGE)

    dst.mkdir(parents=True, exist_ok=True)
    kinds: list[tuple[str, str | None, str | None]] = [
        ("raw", None, None),
        (
            "archive_member",
            "sha256:" + "a" * 64,
            "inner/m1.jsonl",
        ),
        ("precompressed", None, None),
    ]
    lines: list[str] = []
    for i, (kind, container, member) in enumerate(kinds):
        payload = (
            json.dumps({"type": "start_game", "game_id": f"synth-{i}"}, separators=(",", ":"))
            + "\n"
            + json.dumps({"type": "dahai", "pai": 5}, separators=(",", ":"))
            + "\n"
            + json.dumps({"type": "end_game"}, separators=(",", ":"))
            + "\n"
        ).encode()
        compressed = zstd.ZstdCompressor(level=3).compress(payload)
        rel = f"obj-{i}.mjai.json.zst"
        (dst / rel).write_bytes(compressed)

        def _digest(data: bytes) -> str:
            return "sha256:" + hashlib.sha256(data).hexdigest()

        fields: dict[str, object] = {
            "source_kind": kind,
            "source_container_sha256": container,
            "source_member_path": member,
            "source_bytes_sha256": _digest(payload),
            "source_bytes_length": len(payload),
            "compressed_path": rel,
            "compressed_bytes_sha256": _digest(compressed),
            "compressed_bytes_length": len(compressed),
            "decoded_bytes_sha256": _digest(payload),
            "decoded_bytes_length": len(payload),
            "record_count": 3,
            "canonical_jsonl": True,
            "packager_identity": _digest(b"synthetic-packager"),
            "packager_config_hash": _digest(b"synthetic-config"),
            "created_at_utc": "2024-01-01T00:00:00Z",
        }
        ordered = {"packaged_object_id": "sha256:" + "0" * 64, **fields}
        lines.append(json.dumps(ordered, separators=(",", ":"), ensure_ascii=False))
    (dst / "corpus.manifest.jsonl").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dst


def _run_hook(
    cargo: str,
    inputs: list[Path],
    out: Path,
    seal_only: bool,
    artifact_root: Path | None,
) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ)
    env["SEAL_REPLAY_INPUTS"] = os.pathsep.join(str(p) for p in inputs)
    env["SEAL_REPLAY_OUT"] = str(out)
    if seal_only:
        env["SEAL_REPLAY_SEAL_ONLY"] = "1"
    else:
        env.pop("SEAL_REPLAY_SEAL_ONLY", None)
    if artifact_root is not None:
        env["SEAL_REPLAY_ARTIFACT_ROOT"] = str(artifact_root)
    else:
        env.pop("SEAL_REPLAY_ARTIFACT_ROOT", None)
    return subprocess.run(
        [cargo, "nextest", "run", "-p", "hydra-feed", HOOK_FILTER],
        cwd=WORKSPACE,
        env=env,
        capture_output=True,
        text=True,
        timeout=600,
    )


def _run_rust_gate(cargo: str) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ)
    for key in (
        "SEAL_REPLAY_INPUTS",
        "SEAL_REPLAY_OUT",
        "SEAL_REPLAY_SEAL_ONLY",
        "SEAL_REPLAY_ARTIFACT_ROOT",
    ):
        env.pop(key, None)
    return subprocess.run(
        [cargo, "nextest", "run", "-p", "hydra-feed", ROWS_GATE_FILTER],
        cwd=WORKSPACE,
        env=env,
        capture_output=True,
        text=True,
        timeout=600,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="B3 seal-replay: corpus in -> JCS-only manifests out + report JSON (fail-closed)."
    )
    parser.add_argument(
        "--corpus",
        action="append",
        default=[],
        metavar="PATH",
        help="Corpus manifest file or dir (repeatable).",
    )
    parser.add_argument(
        "--real-manifest",
        action="append",
        default=[],
        metavar="PATH",
        help="Real packager manifest path (repeatable; read in place, never vendored).",
    )
    parser.add_argument(
        "--init-synthetic",
        metavar="DIR",
        default=None,
        help="Generate the 3-object synthetic TODAY corpus into DIR first.",
    )
    parser.add_argument("--out", required=True, help="Output dir for JCS manifests + report.json.")
    parser.add_argument(
        "--report",
        default=None,
        help="Report JSON path (default: <out>/report.json).",
    )
    parser.add_argument(
        "--artifact-root",
        default=None,
        metavar="DIR",
        help="Output root for bare relative compressed_path entries (real packager "
        "manifests; mirrors ingest output_root).",
    )
    parser.add_argument(
        "--seal-only",
        action="store_true",
        help="Replay seals + joins only (manifest-only corpora).",
    )
    parser.add_argument(
        "--no-rust-gate",
        action="store_true",
        help="Skip the rows KAT gate step (records skipped; default runs it).",
    )
    parser.add_argument("--cargo", default="cargo", help="Cargo binary (default: cargo).")
    args = parser.parse_args(argv)

    if shutil.which(args.cargo) is None:
        return _fail_usage(f"cargo not found: {args.cargo!r}")

    inputs: list[Path] = []
    if args.init_synthetic:
        try:
            synth = _synthetic_corpus(Path(args.init_synthetic))
        except SystemExit as exc:
            return int(exc.code) if exc.code is not None else EXIT_USAGE
        inputs.append(synth)
    for raw in [*args.corpus, *args.real_manifest]:
        candidate = Path(raw)
        if not candidate.exists():
            return _fail_usage(f"corpus input missing (no silent skip): {raw}")
        inputs.append(candidate)
    if not inputs:
        return _fail_usage("no corpus inputs (pass --corpus and/or --real-manifest)")

    artifact_root: Path | None = None
    if args.artifact_root:
        artifact_root = Path(args.artifact_root)
        if not artifact_root.is_dir():
            return _fail_usage(f"--artifact-root not a dir: {args.artifact_root}")
        artifact_root = artifact_root.resolve()

    out = Path(args.out)
    try:
        out_resolved = out.resolve()
        for candidate in inputs:
            if candidate.is_dir():
                try:
                    out_resolved.relative_to(candidate.resolve())
                except ValueError:
                    pass
                else:
                    return _fail_usage(f"--out {out} lives inside corpus input {candidate}")
            elif out_resolved == candidate.resolve():
                return _fail_usage(f"--out {out} collides with corpus input {candidate}")
        out.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        return _fail_usage(f"cannot prepare --out {out}: {exc}")

    report_path = Path(args.report) if args.report else out / "report.json"

    proc = _run_hook(
        args.cargo, [p.resolve() for p in inputs], out.resolve(), args.seal_only, artifact_root
    )
    if proc.returncode != 0:
        print("seal_replay: Rust replay hook FAILED (fail-closed):", file=sys.stderr)
        print(proc.stdout[-4000:], file=sys.stderr)
        print(proc.stderr[-4000:], file=sys.stderr)
        return EXIT_DIVERGENCE

    gate_status = "skipped"
    if not args.no_rust_gate:
        gate = _run_rust_gate(args.cargo)
        if gate.returncode != 0:
            print("seal_replay: rows KAT gate FAILED (fail-closed):", file=sys.stderr)
            print(gate.stdout[-4000:], file=sys.stderr)
            print(gate.stderr[-4000:], file=sys.stderr)
            return EXIT_DIVERGENCE
        gate_status = "green"

    hook_report = out / "report.json"
    if not hook_report.is_file():
        print(
            f"seal_replay: hook produced no report at {hook_report} (fail-closed)",
            file=sys.stderr,
        )
        return EXIT_DIVERGENCE
    if hook_report.resolve() != report_path.resolve():
        report_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(hook_report, report_path)
    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"seal_replay: unreadable report {report_path}: {exc} (fail-closed)", file=sys.stderr)
        return EXIT_DIVERGENCE
    if not isinstance(report, dict):
        print(f"seal_replay: report not an object (fail-closed): {report_path}", file=sys.stderr)
        return EXIT_DIVERGENCE
    for key in ("reminted", "rejoined", "mismatches", "seal_failures"):
        if key not in report:
            print(
                f"seal_replay: report missing {key!r} (fail-closed): {report_path}",
                file=sys.stderr,
            )
            return EXIT_DIVERGENCE
    if not isinstance(report["reminted"], int) or not isinstance(report["rejoined"], int):
        print(f"seal_replay: report counts malformed (fail-closed): {report_path}", file=sys.stderr)
        return EXIT_DIVERGENCE
    if not isinstance(report["mismatches"], list) or not isinstance(report["seal_failures"], list):
        print(
            f"seal_replay: report detail lists malformed (fail-closed): {report_path}",
            file=sys.stderr,
        )
        return EXIT_DIVERGENCE

    mode = report.get("mode", "full")
    print(
        f"seal-replay: reminted={report['reminted']} rejoined={report['rejoined']} "
        f"mismatches={len(report['mismatches'])} "
        f"seal_failures={len(report['seal_failures'])} mode={mode} "
        f"rust_gate={gate_status} -> {report_path}"
    )
    for entry in [*report["seal_failures"], *report["mismatches"]]:
        print(f"seal-replay: RED {entry}")
    if report["mismatches"] or report["seal_failures"]:
        return EXIT_DIVERGENCE
    for manifest in report.get("manifests", []):
        print(f"seal-replay: out {manifest.get('out')} rows={manifest.get('rows')}")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
